# Generated by Django 5.0.3 on 2024-05-06 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_remove_news_upload_time_news_autor_news_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='autor',
            field=models.CharField(default='', max_length=24),
        ),
    ]
